# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from calculate_position_pkg/image_points.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class image_points(genpy.Message):
  _md5sum = "d50612e5b17d5b27e8f9e37d8fc9f6f6"
  _type = "calculate_position_pkg/image_points"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 x1
int32 x2
int32 x3
int32 x4
int32 y1
int32 y2
int32 y3
int32 y4"""
  __slots__ = ['x1','x2','x3','x4','y1','y2','y3','y4']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x1,x2,x3,x4,y1,y2,y3,y4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(image_points, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x1 is None:
        self.x1 = 0
      if self.x2 is None:
        self.x2 = 0
      if self.x3 is None:
        self.x3 = 0
      if self.x4 is None:
        self.x4 = 0
      if self.y1 is None:
        self.y1 = 0
      if self.y2 is None:
        self.y2 = 0
      if self.y3 is None:
        self.y3 = 0
      if self.y4 is None:
        self.y4 = 0
    else:
      self.x1 = 0
      self.x2 = 0
      self.x3 = 0
      self.x4 = 0
      self.y1 = 0
      self.y2 = 0
      self.y3 = 0
      self.y4 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.x1, _x.x2, _x.x3, _x.x4, _x.y1, _x.y2, _x.y3, _x.y4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.x1, _x.x2, _x.x3, _x.x4, _x.y1, _x.y2, _x.y3, _x.y4,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.x1, _x.x2, _x.x3, _x.x4, _x.y1, _x.y2, _x.y3, _x.y4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.x1, _x.x2, _x.x3, _x.x4, _x.y1, _x.y2, _x.y3, _x.y4,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
