// Generated by gencpp from file realtime_detect_pkg/image_points.msg
// DO NOT EDIT!


#ifndef REALTIME_DETECT_PKG_MESSAGE_IMAGE_POINTS_H
#define REALTIME_DETECT_PKG_MESSAGE_IMAGE_POINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace realtime_detect_pkg
{
template <class ContainerAllocator>
struct image_points_
{
  typedef image_points_<ContainerAllocator> Type;

  image_points_()
    : x1(0)
    , x2(0)
    , x3(0)
    , x4(0)
    , y1(0)
    , y2(0)
    , y3(0)
    , y4(0)  {
    }
  image_points_(const ContainerAllocator& _alloc)
    : x1(0)
    , x2(0)
    , x3(0)
    , x4(0)
    , y1(0)
    , y2(0)
    , y3(0)
    , y4(0)  {
  (void)_alloc;
    }



   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _x2_type;
  _x2_type x2;

   typedef int32_t _x3_type;
  _x3_type x3;

   typedef int32_t _x4_type;
  _x4_type x4;

   typedef int32_t _y1_type;
  _y1_type y1;

   typedef int32_t _y2_type;
  _y2_type y2;

   typedef int32_t _y3_type;
  _y3_type y3;

   typedef int32_t _y4_type;
  _y4_type y4;





  typedef boost::shared_ptr< ::realtime_detect_pkg::image_points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realtime_detect_pkg::image_points_<ContainerAllocator> const> ConstPtr;

}; // struct image_points_

typedef ::realtime_detect_pkg::image_points_<std::allocator<void> > image_points;

typedef boost::shared_ptr< ::realtime_detect_pkg::image_points > image_pointsPtr;
typedef boost::shared_ptr< ::realtime_detect_pkg::image_points const> image_pointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realtime_detect_pkg::image_points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realtime_detect_pkg::image_points_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realtime_detect_pkg::image_points_<ContainerAllocator1> & lhs, const ::realtime_detect_pkg::image_points_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.x2 == rhs.x2 &&
    lhs.x3 == rhs.x3 &&
    lhs.x4 == rhs.x4 &&
    lhs.y1 == rhs.y1 &&
    lhs.y2 == rhs.y2 &&
    lhs.y3 == rhs.y3 &&
    lhs.y4 == rhs.y4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realtime_detect_pkg::image_points_<ContainerAllocator1> & lhs, const ::realtime_detect_pkg::image_points_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realtime_detect_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realtime_detect_pkg::image_points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realtime_detect_pkg::image_points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realtime_detect_pkg::image_points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d50612e5b17d5b27e8f9e37d8fc9f6f6";
  }

  static const char* value(const ::realtime_detect_pkg::image_points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd50612e5b17d5b27ULL;
  static const uint64_t static_value2 = 0xe8f9e37d8fc9f6f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realtime_detect_pkg/image_points";
  }

  static const char* value(const ::realtime_detect_pkg::image_points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x1\n"
"int32 x2\n"
"int32 x3\n"
"int32 x4\n"
"int32 y1\n"
"int32 y2\n"
"int32 y3\n"
"int32 y4\n"
;
  }

  static const char* value(const ::realtime_detect_pkg::image_points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.x2);
      stream.next(m.x3);
      stream.next(m.x4);
      stream.next(m.y1);
      stream.next(m.y2);
      stream.next(m.y3);
      stream.next(m.y4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realtime_detect_pkg::image_points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realtime_detect_pkg::image_points_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    s << indent << "x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x2);
    s << indent << "x3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x3);
    s << indent << "x4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x4);
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
    s << indent << "y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y2);
    s << indent << "y3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y3);
    s << indent << "y4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALTIME_DETECT_PKG_MESSAGE_IMAGE_POINTS_H
